#!/usr/bin/python3

import argparse 
import uuid

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-n", "--n_uuid")
    args = parser.parse_args()
    n = int(args.n_uuid or 1)

    for _ in range(n):
        print(uuid.uuid4())
