#!/usr/bin/python3

import argparse
from datetime import datetime

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-p", "--prefix")
    parser.add_argument("-s", "--suffix")
    parser.add_argument("-e", "--extension")
    args = parser.parse_args()

    vec = []

    if args.prefix is not None:
        pre = str(args.prefix)
        vec.append(pre)

    ts = str(int(datetime.now().timestamp()))
    vec.append(ts)

    if args.suffix is not None:
        suf = str(args.suffix)
        vec.append(suf)

    ext = str(args.extension or "txt")

    name = "-".join(vec)

    print(f"{name}.{ext}")
